language: go

os:
  - linux

sudo: required
dist: trusty
group: deprecated-2017Q4

go:
  - 1.9

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get install -y curl libcurl3 libcurl3-gnutls libcurl4-gnutls-dev; fi
  - $GOPATH/src/github.com/git-time-metric/gtm/script/git2go-init.sh
  - cd $GOPATH/src/github.com/libgit2/git2go
  - make install-static
  - go get github.com/mattn/goveralls

before_deploy:
  - go build -v --tags static -ldflags "-X main.Version=${TRAVIS_TAG}"
  - tar -zcf gtm.${TRAVIS_TAG}.${TRAVIS_OS_NAME}.tar.gz gtm

script:
  - cd $TRAVIS_BUILD_DIR
  - go get -d ./...
  - $HOME/gopath/bin/goveralls -flags=--tags=static -service=travis-ci

